package com.chewy.exception;

public enum NPCErrorCode {
  UNKNOWN,
  NOT_FOUND,
  UNSUCCESSFUL_RESPONSE_CODE,
  EXPIRED_EVENT,
  EXPIRED_PUSH,
  EXPIRED_EMAIL,
  EXPIRED_FAX,
  INVALID_EVENT,
  INVALID_PUSH_EVENT,
  INVALID_EMAIL_EVENT,
  INVALID_FAX_EVENT,
  EMAIL_COMPOSE_FAILURE,
  AWS_FAILURE,
  SERVICE_FAILURE
}
